### ISSUE TITLE
OAuth 2 flows and URLs are lost

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-converter#28]
Converted OAuth 2 securitySchemes are missing `flows`, `authorizationUrl` and possibly other details.

Spec: https://gist.githubusercontent.com/hkosova/043a4edbca522056e60292f4658fb889/raw/9a564bc9b645cff93698850301822470fee6832e/auth.yaml
```yaml
...
securityDefinitions:
  ...
  OAuth2Implicit:
    type: oauth2
    authorizationUrl: http://swagger.io/api/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
...
```

Converted spec: http://oai.swagger.io/api/convert?url=https://gist.githubusercontent.com/hkosova/043a4edbca522056e60292f4658fb889/raw/9a564bc9b645cff93698850301822470fee6832e/auth.yaml
```
"OAuth2Implicit": {
  "type": "oauth2"
}
```

Expected result:
```
"OAuth2Implicit": {
    "type": "oauth2",
    "flows": {
      "implicit": {
        "authorizationUrl": "http://swagger.io/api/oauth/dialog",
        "scopes": {
          "write:pets": "modify pets in your account",
          "read:pets": "read your pets"
        }
      }
    }
  }
```
