### ISSUE TITLE
Missing default parameter values

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-converter#6]
The `default` value of query parameters is not converted. I did not check other parameter types.

Original spec:
https://raw.githubusercontent.com/swagger-api/swagger-editor/2.x/spec-files/heroku-pets.yaml
```
paths:
  /:
    get:
      parameters:
        - name: limit
          in: query
          description: number of pets to return
          type: integer
          default: 11      # <--------
          minimum: 11
          maximum: 10000
```

Converted spec:
http://oai.swagger.io/api/convert?url=https://raw.githubusercontent.com/swagger-api/swagger-editor/2.x/spec-files/heroku-pets.yaml
```
"paths": {
  "/": {
    "get": {
      "parameters": [{
          "name": "limit",
          "in": "query",
          "description": "number of pets to return",
          "schema": {
            "maximum": 10000,
            "minimum": 11,
            "type": "integer"
          }
        }
```
**Actual result:** Parameter `schema` is missing the `default` value.

**Expected result:**
```
          "schema": {
            "default": 11,     // <----------
            "maximum": 10000,
            "minimum": 11,
            "type": "integer"
          }
```
