### ISSUE TITLE
Enum Values 'TRUE' and 'FALSE' are converted Incorrectly in yaml

### ISSUE THREAD

**Issue by fibsifan** [swagger-api/swagger-converter#61]
When converting 2.0 enum values to 3.0 using the converter API hosted at https://converter.swagger.io/api/convert the necessary escaping for string values `'TRUE'` and `'FALSE'` gets lost in the Process.

example input (excerpt):
```yaml
definitions:
  Element:
    properties:
      tristate:
        - 'TRUE'
        - 'FALSE'
        - EMPTY
```

output
```yaml
components:
  schemas:
    Element:
      properties:
        tristate:
          - TRUE
          - FALSE
          - EMPTY
```

TRUE and FALSE are yaml boolean literals that need to be escaped, see https://yaml.org/type/bool.html
