### ISSUE TITLE
Validator throws error for external references

### ISSUE THREAD

**Issue by bhardwz** [swagger-api/swagger-converter#65]
I have a Swagger file which has external references.
Here is a snapshot of how I am calling out the external reference:

```
200:
      description: "Success"
      schema:
            $ref: "../../schema/car.yml#/definitions/services.CarMetadata"

```

Now Swagger Editor is not throwing error but, when I'm converting to swagger 3.0, I get this error: 

```
---
- "malformed or unreadable swagger supplied"
```

This only comes up when I have external references in configuration.
Please look at this.
